### ISSUE TITLE
Any plans to update for the SotV dlc

### ISSUE THREAD

**Issue by Yolad** [wildbook/R2Mods#38]
Would like to see TooManyFriends mod updated

**Comment by orehmane** [comment]
Chiming in to support this! Great mod, and we're missing it after the SotV release.

**Comment by KitBallard64** [comment]
Indeed! Adding my note here as well. Would love to get a community event for my stream at some point and having more than 4 would make things batty.

~Kito

**Comment by HudsonAkridge** [comment]
I took a look at this yesterday, and a decent amount would need to change to get it to work going forward with the new DLLs/DLC.

Check out the code from [NotEnoughFriends](https://github.com/Bubbet/Risk-Of-Rain-Mods/tree/master/NotEnoughFriends), it's also available on [thunderstore](https://thunderstore.io/package/Bubbet/NotEnoughFriends/). It works with the DLC and supports up to 16 players.

I tested it last night with a group of 6 or 7 and it worked great.

**Comment by wildbook** [comment]
I'm planning to eventually update it (or merge a PR if someone beats me to it), I just haven't had the time to yet. From what I've seen so far the changes required should be pretty minor, and the main reason it broke seems to be that the latest update changed the name of the game's main .dll.

I've been mostly out of the RoR2 modding scene for the past year or so since I haven't had as much time, so I need to catch up when it comes to tooling and changes that I've missed.  I'll see if I can look into it and hopefully get the mods working again this weekend.

**Comment by KitBallard64** [comment]
Good luck Wild! I hope it goes well for you and with little headaches.

~Kito

**Comment by wildbook** [comment]
I've pushed an update to all three mods now, and in theory they should all work again.

I don't have the time to test them past the very basics right now, so if you run into any issues just poke here or open a new issue and I'll check it out and fix what I can. 

Hopefully they all work just fine :)

**Comment by oorzkws** [comment]
> I've pushed an update to all three mods now, and in theory they should all work again.
> 
> I don't have the time to test them past the very basics right now, so if you run into any issues just poke here or open a new issue and I'll check it out and fix what I can.
> 
> Hopefully they all work just fine :)

Thanks! I finished Mithrix but the escape sequence didn't trigger, the final sequence charged fine but once it finished charging nothing happened and the timer expired a minute or so later (counted as defeat).
